apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
spec:
  type: NodePort
  selector:
    app: loyalty-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30080